# 1. 讀取 Render 的 DATABASE_URL，並在尾端強制加上 SSL 加密連線
spring.datasource.url=${DATABASE_URL}?sslmode=require

# 2. 讓程式去讀取你 Render 後台設定的帳號與密碼變數
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 3. 驅動與資料庫平台設定（你原本的設定）
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.data-locations=classpath:data-prod.sql

# 4. 加上 DDL 自動更新（確保雲端啟動時會自動在資料庫建立資料表）
spring.jpa.hibernate.ddl-auto=update